server:
  port: ${SERVER_PORT}
  servlet:
    context-path: '/firstPlaceHealth/'  
spring:
  application:
    name: first-place-Health-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
      
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update 
            
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html      

openapi:
  server:
    url: ${OPEN_API_SERVER_URL}
           
           
#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always      