server:
  port: 8082
  servlet:
    context-path: '/firstPlaceHealth/'  
spring:
  application:
    name: first-place-Health-service
  datasource:
    url: jdbc:postgresql://localhost:5432/firstPlaceHealth
    username: admin
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hobernate.dialect.PostgreSQLDialect
    jdbc: 
      lob.non-contextual-creation: true
      type:
          descriptor:
            sql:trace
            
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html      
           
#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always      